### ISSUE TITLE
A valid query string passed to parseQuery should begin with '?'

### ISSUE THREAD

**Issue by mogaoyong** [cenkai88/vue-svg-icon#14]
按照文档，在main.js中加入如下代码

import 'font-awesome/css/font-awesome.css';
import Icon from 'vue-svg-icon/Icon.vue';

执行npm run dev命令，控制台打印出如下信息，该如何解决呢?
-------------------------------------------------------------------------------------------------------------------
 warning  in ./src/svg/14.svg

Module build failed: Error: A valid query string passed to parseQuery should begin with '?'
    at Object.parseQuery (D:\vue\vux-simple\node_modules\_loader-utils@1.1.0@loader-utils\lib\parseQuery.js:13:9)
    at Object.module.exports (D:\vue\vux-simple\node_modules\xml-loader\index.js:12:29)

 @ ./src/svg ./~/xml-loader! ^\.\/.*\.svg$
 @ ./~/_babel-loader@6.4.1@babel-loader/lib!./~/_vux-loader@1.1.2@vux-loader/src/script-loader.js!./~/_vue-loader@11.3.4@vue-loa
der/lib/selector.js?type=script&index=0!./~/vue-svg-icon/Icon.vue
 @ ./~/vue-svg-icon/Icon.vue
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

**Comment by btshj** [comment]
请问，你解决了吗?我也遇到了这个情况
